author(betsy_beyer,site_reliability_engineering).
author(bruce_tate,seven_languages_in_seven_weeks).
author(kent_beck,extreme_programming_explained).
author(kent_beck,test-driven_development_by_example).
author(martin_fowler,planning_extreme_programming).
author(martin_fowler,refactoring).
author(paul_duvall,continuous_integration).
author(sam_newman,building_microservices).
author(sam_newman,monolith_to_microservices).
author(tom_demarco,adrenaline_junkies).
author(tom_demarco,peopleware).
author(tom_demarco,the_deadline).
